# 端口号
server:
  port: 9091
  servlet:
    context-path: /second-hand


# 热部署
spring:
  devtools:
    livereload:
      enabled: true
  # 数据库
  datasource:
    username: root
    password: root
    url: jdbc:p6spy:mysql://47.93.117.14:3306/secondhand?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.p6spy.engine.spy.P6SpyDriver    #    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
#    redis配置
  redis:
    database: 0
#    host: 47.93.117.14
    host: 172.17.0.3
#    host : localhost
    port: 6379
    password:
    timeout: 10000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 30      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
  static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 10MB #上传文件大小为10MB

# 日志记录
logging:
  config: classpath:logback.xml
  level:
    root: info

# shiro相关配置
shiro:
  loginUrl: /tokenExpired
  unauthorizedUrl: /noauth
  web:
    enabled: true

security:
  token_secretKey: 123456


# mybatis 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  #  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: com.ypzx.ypzxbis.module
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

resources:
    path: /file/secondhand
    productsPath: images/products
    noticePath: images/notice